# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "lfx-mcp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lfx-mcp.labels" . | nindent 4 }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gateway.name }}
      namespace: {{ .Release.Namespace }}
  hostnames:
    - {{ .Values.gateway.listeners.https.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: {{ include "lfx-mcp.fullname" . }}
          port: {{ .Values.service.port }}
          weight: 1
